sudo: required
services:
  - docker

before_install:
  - docker build -t ismaaa/docker-react -f Dockerfile.dev .

script:
  - docker run ismaaa/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-054227592552"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
