version: '3'
services:
  web:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - /app/node_modules # Don't override this folder
      - .:/app # {current working directory}:{where to mount the directory}
    command: ["npm", "run", "test"]
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # Don't override this folder
      - .:/app # {current working directory}:{where to mount the directory}
    command: ["npm", "run", "test"]
